"""add_submodule_and_topic_content

Revision ID: bfe3b5e0a395
Revises: 3707269d339c
Create Date: 2026-05-20 11:06:01.359014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe3b5e0a395'
down_revision: Union[str, None] = '3707269d339c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submodules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('topics', sa.Column('submodule_id', sa.UUID(), nullable=False))
    op.add_column('topics', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('topics', sa.Column('content_filename', sa.String(length=255), nullable=True))
    op.drop_constraint('topics_module_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'submodules', ['submodule_id'], ['id'], ondelete='CASCADE')
    op.drop_column('topics', 'description')
    op.drop_column('topics', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_module_id_fkey', 'topics', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('topics', 'content_filename')
    op.drop_column('topics', 'content')
    op.drop_column('topics', 'submodule_id')
    op.drop_table('submodules')
    # ### end Alembic commands ###
